pool: General

steps:
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: 'Azure Live'
      keyVaultName: 'UKHOKeyvault'
      secretsFilter: "UKHOCodeSigningCert"
  - powershell: |
      $kvSecretBytes = [System.Convert]::FromBase64String('$(UKHOCodeSigningCert)')
      write-host $kvSecretBytes
      $certCollection = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2Collection 
      $certCollection.Import($kvSecretBytes,$null,[System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)
      $protectedCertificateBytes = $certCollection.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pkcs12, $password)
      [System.IO.File]::WriteAllBytes("$(system.DefaultWorkingDirectory)/cert.pfx", $protectedCertificateBytes)
    env:
      password : $(password)