variables:
  pfxLocation : $(system.DefaultWorkingDirectory)/cert.pfx

pool: General

steps:
  - powershell: dotnet build ./src
    displayName: Build Source Code
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: 'Azure Live'
      keyVaultName: 'UKHOKeyvault'
      secretsFilter: "UKHOCodeSigningCert"
    displayName: Download secrets from Azure Key Vault
  - powershell: |
      ./generatePfx.ps1 `
        -pfxString $(UKHOCodeSigningCert) 
    env:
      pfxPassword : $(password)
    displayName: Generate PFX
  - powershell: ./sign.ps1 -pfxPath $pfxPath
    displayName: Sign DLLs and exe